### PR TITLE
Private events project

### PR DESCRIPTION
**Pull request by sanadwj**
## This PR for:

- Create a new rails app to handle events
- Add dB for each model 
- Create an association between the users and the events and the attendees
- Create validation for the user 
- Add layouts for the app

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @sanadwj and @wrakc, great job with this project :+1: Descriptive commit messages and README :slightly_smiling_face: Kindly address the comments below so we get our project approved :+1: Great job :fireworks: 

- Do not make any changes to the linter files. Let us use the right linter configuration for this project, kindly check this [link](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml) for the right config
- Let us create a view helper for our view logic. There should be no logic in our views
- `Events controller` index action
  - lists past events, i.e. @past_events = Event.previous_events
  - lists ucomping events, i.e. `@upcoming_events = Event.upcoming_events`
- `Users controller` show action
  - lists events created by user, i.e. `@created_events = current_user.events`
  - lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous`
  - lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming`

Kindly address these and submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by carlosveigadev** [comment]
Hi @addod19, we improved the code as suggested.
- Update linter files;
- Remove logic from views;
- Add helper methods.

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @sanadwj and @wrakc! I'd like to start by commending you for working on the feedback from the last review. However, there appears to be some feedback that my colleague forgot to include in the last review. We apologize for the inconvenience but I have included it below since it is vital that you consider it for this project.
- [x] Add `.idea` and `.generators` to your `.gitignore` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] __[Optional]__ Add unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [ ] __[Optional]__ Add integration tests (for authentication and event managment features) (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by carlosveigadev** [comment]
Thanks for the review @trekab, we improved the required changes as suggested.

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved :heavy_check_mark:
### You have done a good job :+1: by implementing the required changes. This project is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

**Pull request merged**
